const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('abra', {
  providerConfig: () => ipcRenderer.invoke('abra:provider-config'),
  agentTicket: () => ipcRenderer.invoke('abra:agent-ticket'),
  exportInstaller: () => ipcRenderer.invoke('abra:export-installer'),
  agentList: () => ipcRenderer.invoke('abra:agent-list'),
  agentSelect: id => ipcRenderer.invoke('abra:agent-select', id),
  sandbox: (action, payload) => ipcRenderer.invoke('abra:sandbox', action, payload),
  local: args => ipcRenderer.invoke('abra:local', args),
  remote: args => ipcRenderer.invoke('abra:remote', args),
  config: () => ipcRenderer.invoke('abra:config'),
  chooseWorkspace: () => ipcRenderer.invoke('abra:choose-workspace'),
  appTarget: (name, sessionId) => ipcRenderer.invoke('abra:app-target', name, sessionId),
  appStart: workspace => ipcRenderer.invoke('abra:app-start', workspace),
  appStop: () => ipcRenderer.invoke('abra:app-stop'),
  appStatus: () => ipcRenderer.invoke('abra:app-status'),
  appOpen: () => ipcRenderer.invoke('abra:app-open'),
  egressStart: () => ipcRenderer.invoke('abra:egress-start'),
  egressStop: () => ipcRenderer.invoke('abra:egress-stop'),
  egressStatus: () => ipcRenderer.invoke('abra:egress-status'),
  novncStart: () => ipcRenderer.invoke('abra:novnc-start'),
  novncStop: () => ipcRenderer.invoke('abra:novnc-stop'),
  novncStatus: () => ipcRenderer.invoke('abra:novnc-status'),
  novncOpen: () => ipcRenderer.invoke('abra:novnc-open'),
});
